apiVersion: v1
kind: Secret
metadata:
  name: exam-client-jwt
  namespace: kafka
  labels:
    konghq.com/credential: jwt
stringData:
  congig: |
    {
      "key": "exam-client-key",
      "secret": "supersecret",
      "algorithm": "HS256"
    }
  konsumerRef: exam-client