# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: producer-ingress
#   namespace: kafka
#   annotations:
#     #konghq.com/strip-path: "true"
# spec:
#   ingressClassName: kong  
#   rules:
#   - host: producer.local
#     http:
#       paths:
#       - path: /event
#         pathType: Prefix
#         backend:
#           service:
#             name: producer-service
#             port:
#               number: 5000


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: producer-ingress
  namespace: kafka
  annotations:
    konghq.com/plugins: jwt-auth
    #konghq.com/strip-path: "true"
spec:
  ingressClassName: kong  
  rules:
  - host: producer.192.168.49.2.nip.io
    http:
      paths:
        - path: /event
          pathType: Prefix
          backend:
            service:
              name: producer-service
              port:
                number: 5000
